name: pipeline production

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/app-prod

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/app-prod

  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Docker Pull and run from Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_DNS}}
          username: ubuntu
          key: ${{secrets.AWS_PK}}
          envs: GITHUB_SHA
          script: |
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/app-prod
            sudo docker stop app-prod
            sudo docker rm app-prod
            sudo docker run --detach -p 3000:3000 --name app-prod ${{secrets.DOCKER_USERNAME}}/app-prod
